D = Steep::Diagnostic

target :lox do
  check "lib"
  signature "sig"

  configure_code_diagnostics(D::Ruby.strict)       # `strict` diagnostics setting
  # configure_code_diagnostics(D::Ruby.lenient)      # `lenient` diagnostics setting
end
