class Environment
  class EnvironmentError < LoxError
    attr_reader token: Token

    def initialize: (Token token, String message) -> void
  end

  @values: Hash[String, lox_value]
  @enclosing: Environment | nil

  def initialize: (?Environment? enclosing) -> void

  def define: (String name, lox_value value) -> void

  def get: (Token token) -> lox_value

  def assign: (Token name, lox_value value) -> void
end
